// ── Sharing Utilities ─────────────────────────────────────────────────────────

export function encodeParamsToUrl(params: Record<string, string | number | boolean>): string {
  const searchParams = new URLSearchParams();
  Object.entries(params).forEach(([k, v]) => searchParams.set(k, String(v)));
  const url = new URL(window.location.href);
  url.search = searchParams.toString();
  return url.toString();
}

export function decodeParamsFromUrl(): Record<string, string> {
  if (typeof window === 'undefined') return {};
  const params: Record<string, string> = {};
  new URLSearchParams(window.location.search).forEach((v, k) => { params[k] = v; });
  return params;
}

export async function copyShareUrl(params: Record<string, string | number | boolean>): Promise<boolean> {
  try {
    const url = encodeParamsToUrl(params);
    await navigator.clipboard.writeText(url);
    return true;
  } catch {
    return false;
  }
}

export function downloadResultsAsPDF(
  title: string,
  results: { label: string; value: string; sub?: string }[],
  inputs: { label: string; value: string }[],
  disclaimer?: string
) {
  const content = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} — Plain Figures</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Courier New', monospace; background: #fff; color: #111; padding: 40px; font-size: 13px; }
    .header { border-bottom: 2px solid #111; padding-bottom: 16px; margin-bottom: 24px; }
    .brand { font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: #666; margin-bottom: 8px; }
    h1 { font-size: 20px; font-weight: normal; letter-spacing: -0.02em; }
    .date { font-size: 10px; color: #666; margin-top: 4px; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 10px; text-transform: uppercase; letter-spacing: 0.12em; color: #666; border-bottom: 1px solid #eee; padding-bottom: 6px; margin-bottom: 12px; }
    .result-row { display: flex; justify-content: space-between; align-items: baseline; padding: 8px 0; border-bottom: 1px solid #f0f0f0; }
    .result-label { color: #444; }
    .result-value { font-size: 15px; font-weight: bold; }
    .result-sub { font-size: 10px; color: #888; margin-top: 2px; }
    .input-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f5f5f5; color: #666; }
    .disclaimer { margin-top: 32px; padding: 12px; background: #f8f8f8; border-left: 3px solid #ddd; font-size: 10px; color: #888; line-height: 1.6; }
    .footer { margin-top: 24px; font-size: 10px; color: #aaa; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">Plain Figures — plainfigures.org</div>
    <h1>${title}</h1>
    <div class="date">Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </div>
  <div class="section">
    <div class="section-title">Results</div>
    ${results.map(r => `<div class="result-row"><div><div class="result-label">${r.label}</div>${r.sub ? `<div class="result-sub">${r.sub}</div>` : ''}</div><div class="result-value">${r.value}</div></div>`).join('')}
  </div>
  <div class="section">
    <div class="section-title">Inputs Used</div>
    ${inputs.map(i => `<div class="input-row"><span>${i.label}</span><span>${i.value}</span></div>`).join('')}
  </div>
  <div class="disclaimer">${disclaimer || 'These calculations are indicative only and do not constitute financial advice. Always consult a qualified financial adviser before making decisions.'}<br><br>Plain Figures — plainfigures.org</div>
  <div class="footer">Generated by Plain Figures · plainfigures.org · ${new Date().toISOString()}</div>
</body>
</html>`;

  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `plainfigures-${title.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateShareImage(
  title: string,
  results: { label: string; value: string }[],
  accentColor: string = '#3b82c4'
): string {
  const canvas = document.createElement('canvas');
  canvas.width = 1200;
  canvas.height = 630;
  const ctx = canvas.getContext('2d')!;

  ctx.fillStyle = '#0a0e14';
  ctx.fillRect(0, 0, 1200, 630);

  ctx.strokeStyle = 'rgba(255,255,255,0.03)';
  ctx.lineWidth = 1;
  for (let x = 0; x < 1200; x += 60) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, 630); ctx.stroke(); }
  for (let y = 0; y < 630; y += 60) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(1200, y); ctx.stroke(); }

  ctx.fillStyle = accentColor;
  ctx.fillRect(0, 0, 6, 630);

  ctx.fillStyle = 'rgba(255,255,255,0.3)';
  ctx.font = '14px "Courier New", monospace';
  ctx.fillText('PLAIN FIGURES · PLAINFIGURES.ORG', 60, 60);

  ctx.fillStyle = '#e8edf5';
  ctx.font = '300 42px "Courier New", monospace';
  ctx.fillText(title, 60, 140);

  ctx.strokeStyle = 'rgba(255,255,255,0.1)';
  ctx.lineWidth = 1;
  ctx.beginPath(); ctx.moveTo(60, 170); ctx.lineTo(1140, 170); ctx.stroke();

  const cols = Math.min(4, results.length);
  const colW = (1140 - 60) / cols;

  results.slice(0, 4).forEach(({ label, value }, i) => {
    const x = 60 + i * colW;
    ctx.fillStyle = 'rgba(255,255,255,0.35)';
    ctx.font = '12px "Courier New", monospace';
    ctx.fillText(label.toUpperCase(), x, 220);
    ctx.fillStyle = accentColor;
    ctx.font = `300 ${value.length > 12 ? '28px' : '36px'} "Courier New", monospace`;
    ctx.fillText(value, x, 275);
  });

  ctx.fillStyle = 'rgba(255,255,255,0.15)';
  ctx.font = '12px "Courier New", monospace';
  ctx.fillText(`Calculated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, 60, 590);
  ctx.fillText('No advice. No noise. Just the maths.', 700, 590);

  return canvas.toDataURL('image/png');
}

export function downloadShareImage(title: string, results: { label: string; value: string }[], accentColor?: string) {
  const dataUrl = generateShareImage(title, results, accentColor);
  const a = document.createElement('a');
  a.href = dataUrl;
  a.download = `plainfigures-${title.toLowerCase().replace(/\s+/g, '-')}.png`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
